/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResultDataImport } from './routes/result/$data'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResultDataRoute = ResultDataImport.update({
  id: '/result/$data',
  path: '/result/$data',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/result/$data': {
      id: '/result/$data'
      path: '/result/$data'
      fullPath: '/result/$data'
      preLoaderRoute: typeof ResultDataImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/result/$data': typeof ResultDataRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/result/$data': typeof ResultDataRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/result/$data': typeof ResultDataRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/result/$data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/result/$data'
  id: '__root__' | '/' | '/result/$data'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResultDataRoute: typeof ResultDataRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResultDataRoute: ResultDataRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/result/$data"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/result/$data": {
      "filePath": "result/$data.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
